Import('env')

build  = env['CONFIG']['global']['build']['draw_data']
source = env['CONFIG']['global']['source']['draw_data']

env.BuildR(target  = ['#%s/data.csv'       % build],
           source  = ['#%s/draw_data.r'        % source],
           log_ext = 'draw_data')
